services:
  postgres:
    image: postgres:16
    container_name: pach-postgres
    restart: unless-stopped
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: pach
      POSTGRES_PASSWORD: pach
      POSTGRES_DB: pach
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
    volumes:
      - pachi_pgdata:/var/lib/postgresql/data

volumes:
  pachi_pgdata:
