export default {
  schemaPath: '../db/schema.ts',
  outputPath: './schema.ts',
  zeroImportPath: '@rocicorp/zero',
  permissions: {
    users: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    companies: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    crm_companies: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    crm_contacts: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    crm_deal_contacts: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    crm_deals: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    crm_notes: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    crm_boards: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    crm_board_columns: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    decks: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    pm_teams: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    pm_projects: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    pm_statuses: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    pm_labels: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    pm_issues: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    pm_issue_labels: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    pm_issue_activity: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    pm_saved_views: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    whatsapp_templates: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    whatsapp_campaigns: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
    whatsapp_messages: { row: { select: ['true'], insert: ['true'], update: ['true'], delete: ['true'] } },
  },
}
