import type { Config } from 'tailwindcss'

const colorVar = (name: string) => ({ opacityValue }: { opacityValue?: string }) => {
  if (opacityValue === undefined) return `rgb(var(--${name}-rgb))`
  return `rgb(var(--${name}-rgb) / ${opacityValue})`
}

export default {
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
    '../tools/decks/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
        sans: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      colors: {
        void: colorVar('bg-0'),
        pit: colorVar('bg-1'),
        'pit-2': colorVar('bg-2'),
        'pit-3': colorVar('bg-3'),
        rim: colorVar('bg-input'),
        phosphor: colorVar('accent'),
        'phosphor-soft': colorVar('accent-soft'),
        'phosphor-deep': colorVar('accent-deep'),
        amber: colorVar('warn'),
        fault: colorVar('fail'),
        'pach-info': colorVar('info'),
        'fg-1': colorVar('fg-1'),
        'fg-2': colorVar('fg-2'),
        'fg-3': colorVar('fg-3'),
        'fg-4': colorVar('fg-4'),
        'bg-0': colorVar('bg-0'),
        'bg-1': colorVar('bg-1'),
        'bg-2': colorVar('bg-2'),
        'bg-3': colorVar('bg-3'),
        'bg-input': colorVar('bg-input'),
        accent: colorVar('accent'),
        'accent-soft': colorVar('accent-soft'),
        'accent-deep': colorVar('accent-deep'),
        'accent-fill': colorVar('accent-fill'),
        edge: colorVar('edge'),
        overlay: colorVar('overlay'),
        ok: colorVar('ok'),
        warn: colorVar('warn'),
        fail: colorVar('fail'),
        info: colorVar('info'),
        // legacy aliases (decks library still imports these)
        'pach': { red: colorVar('accent') },
        'ardia-red': '#F13D43',
      },
      letterSpacing: {
        'label': '0.18em',
        'wide-2': '0.25em',
      },
      opacity: {
        '2': '0.02',
        '3': '0.03',
        '4': '0.04',
        '5': '0.05',
        '6': '0.06',
        '7': '0.07',
        '8': '0.08',
        '10': '0.10',
        '12': '0.12',
        '14': '0.14',
        '15': '0.15',
        '16': '0.16',
        '18': '0.18',
        '20': '0.20',
        '22': '0.22',
        '24': '0.24',
        '25': '0.25',
        '28': '0.28',
        '30': '0.30',
        '32': '0.32',
        '34': '0.34',
        '35': '0.35',
        '36': '0.36',
        '40': '0.40',
        '45': '0.45',
        '50': '0.50',
        '55': '0.55',
        '60': '0.60',
        '65': '0.65',
        '70': '0.70',
        '72': '0.72',
        '75': '0.75',
        '80': '0.80',
        '90': '0.90',
        '95': '0.95',
      },
      boxShadow: {
        'glow-xs': 'var(--glow-xs)',
        'glow-sm': 'var(--glow-sm)',
        'glow-md': 'var(--glow-md)',
        'glow-lg': 'var(--glow-lg)',
        'glow-amber': 'var(--glow-amber)',
        'glow-fault': 'var(--glow-fault)',
        'terminal-panel': 'var(--shadow-panel)',
        'terminal-popover': 'var(--shadow-popover)',
        'terminal-overlay': 'var(--shadow-overlay)',
      },
      animation: {
        'blink': 'pach-blink 1s steps(2,end) infinite',
        'pulse-pach': 'pach-pulse 1.6s ease-in-out infinite',
      },
      keyframes: {
        'pach-blink': { '0%,50%': { opacity: '1' }, '51%,100%': { opacity: '0' } },
        'pach-pulse': { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.5' } },
      },
    },
  },
  plugins: [],
} satisfies Config
